version: '3.9'
services:
  backend:
    build: .
    command: gunicorn run:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: writer_db
      POSTGRES_USER: writer_user
      POSTGRES_PASSWORD: writer_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
